baseURL = ""
languageCode = "en-us"
title = "Resume Exercise"
disableKinds = ["taxonomy", "taxonomyTerm"]
publishDir = "public"

[params]
  author = "Achyut"
  description = "Front-End Developer"

  primaryColor = "#0080ff"
  textPrimaryColor = "#292929"

  [params.profile]
    enable = true
    name = "Achyut"
    tagline = "Front-End Developer"

  [params.contact]
    enable = true
    location = "Ahmedabad, India"
    
    [[params.contact.list]]
    icon = "fab fa-linkedin"
    url = "#"
    text = "Professional Insights"

  [params.summary]
    enable = true
    text = "Total 5+ years of experience in working on Front-End development using ReactJS and JAMstack. I have developed multiple website using various popular technologies. Lately I have been focusing more on front-end technologies. I am always open to work on new technologies or entering new areas with interesting problems to solve and have the ability to respond within 24 hours."

  [params.coreskills]
      enable = true

      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "Bootstrap"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "jQuery"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "Angular"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "AWS"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "NodeJS"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "Docker"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "SASS"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "Javascript"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "Hugo"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "REST API"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "CircleCI"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "GitHub"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "GitLab"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "PostgreSQL"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "Redux"
      [[params.coreskills.list]]
      icon = "far fa-check-square"
      title = "Jekyll"

    [params.projects]
      enable = true

      [[params.projects.list]]
      title = "NS MAAP (News Search Media Aggression & Analysis Platform)"
      meta = ""
      tagline = "An analysis tool that aggregates data from multiple sources be it online or user uploaded. Data is pulled in from sources such as Facebook posts, YouTube videos, Twitter tweets, and Instagram posts based on the tags that the tenant is interested in as per schedule. It is then processed to extract summary, translated to different languages, Sentiment and Hashtag Analyzed, Transcribed (for audio and video). These then appear in searches of the tenant’s client. Various reports can also be pulled from these data"

      [[params.projects.list]]
      title = "The Spectator UK"
      meta = "The Spectator UK"
      tagline = "JAMstack experiment with Hugo and Netlify to build a proof of concept website to replace their current CMS. "

      [[params.projects.list]]
      title = "PricewaterhouseCoopers, Norway"
      meta = ""
      tagline = "Design, Development, CI/CD Setup on Azure, Rmarkdown compatibility, Azure SSO(Single Sign- on), Planning, Execution."

      [[params.projects.list]]
      title = "Thread Learning"
      meta = ""
      tagline = "Hugo based website for marketing and Docs that ranked on the first page for their competitors name. Eventually, got acquired by the same competitor after a year."

      [[params.projects.list]]
      title = "Configrd"
      meta = ""
      tagline = "Hugo Theme Development based on the GitBook Design. Configrd is a SaaS startup and they wanted a GitBook lookalike theme for Hugo to host their documentation on Netlify. The theme is now opensource."

      [[params.projects.list]]
      title = "Record.Digital"
      meta = ""
      tagline = "Record Management as a Service : Jekyll based website for RMaaS hosted on GitHub Pages."

    [params.experience]
        enable = true

        [[params.experience.list]]
        name = "HTML5/CSS3"
        level = "5+ years"
        [[params.experience.list]]
        name = "Javascript"
        level = "5+ years"
        [[params.experience.list]]
        name = "ReactJs"
        level = "3 years"
        [[params.experience.list]]
        name = "Jamstack"
        level = "2 years"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "RDBMS"
        [[params.skills.list.items]]
        details = "Mysql, SqlServer, Oracle, MS Access"
        [[params.skills.list]]
        title = "OS"
        [[params.skills.list.items]]
        details = "Linux, Windows and DOS"
        [[params.skills.list]]
        title = "Web & App Server"
        [[params.skills.list.items]]
        details = "Nginx, LAMP, WAMP, Tomcat, IIS, AWS"
        [[params.skills.list]]
        title = "Graphical Tools"
        [[params.skills.list.items]]
        details = "Adobe Photoshop, Gimp"
        [[params.skills.list]]
        title = "Project Management Tools"
        [[params.skills.list.items]]
        details = "Slack, Jira, Basecamp, Flowdock, Teambox/Redbooth, Redmine, Active-Collab"
        [[params.skills.list]]
        title = "Repository Tools"
        [[params.skills.list.items]]
        details = "Git, Bitbucket, SVN"

    [params.information]
        enable = true

        [[params.information.list]]
        title = "Contributions"
        [[params.information.list.items]]
        details = "Templates"
        [[params.information.list.items]]
        details = "Module & Plugins"

        [[params.information.list]]
        title = "Others"
        details = "Workshops, Seminar"
